[global]
solver_path = "./fvm_euler_1d_solver/nozzle_1d_solver.py"       
savedir = "~/.lwfm/out/fvm-euler-1d-solver"                   
hideplots = true
dump_matrices = false

localdt = true
hhl_scale = "leastsq"       # or "true_sol"
linsolver = "HHL"

[case0]
nelem = 2
backend = "fake fake_brisbane"   # "ideal", "fake fake_brisbane", "fake fake_torino"
shots = 100                      # should run idealized estimation
max_iters = 5
max_inner_iters = 1


