[global]
solver_path = "./fvm_euler_1d_solver/nozzle_1d_solver.py"       
savedir = "~/.lwfm/out/fvm-euler-1d-solver"                   
hideplots = true
dump_matrices = false

linsolver = "HHL"

[case0]
nelem = 5
backend = "ideal"
shots = 0                   # should run idealized estimation
max_iters = 5
max_inner_iters = 1


