[global]
solver_path = "./fvm_euler_1d_solver/nozzle_1d_solver.py"       
savedir = "~/.lwfm/out/fvm-euler-1d-solver"                   
hideplots = true

linsolver = "HHL"
backend = "ideal"
nelem = 2
max_inner_iters = 1

[case1]
max_iters = [1, 2, 6]

