[global]
solver_path = "./fvm_euler_1d_solver/nozzle_1d_solver.py"       
circuit_executor_path = "./wf_circuit_executor.py" 


savedir = "~/.lwfm/out/fvm-euler-1d-solver" 
show_plots = false                         
run_circuit = false                        

linsolver = "HHL"
nelem = 3
cfl = 1e5
localdt = true
max_iters = 1
max_inner_iters = 1
quantum_shots = 100 
quantum_backend = "density_matrix" 

[case0]
quantum_transpile_opt = 0

#[case1]
#quantum_transpile_opt = 1

#[case2]
#quantum_transpile_opt = 2

#[case3]
#quantum_transpile_opt = 3


